import KeypadButton from "../features/home/components/KeypadButton";

const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export const lightTheme = {
  backgroundGradient1: '#1D9CDB',
  backgroundGradient2: '#6CB3D6',
  primary:'#1E85B7',
  secondary:'#98DBEA',
  text: '#fff',
  secondaryText: '#1E85B7',
  background: '#FFFFFF',
  primaryCard:'#FFFFFF',
  positive: '#11B375',
  negative: '#FF6464',
  inputText:'#6B7280',
  inputText2:'#919BAE',
  errorText:'#5F0303',
  keypadButton:'#F1F1F1',
  shadowColor: '#000000',
  borderColor: '#FFFFFF',
  tint: tintColorLight,
  tabIconDefault: '#6B7280',
  tabIconSelected: tintColorLight,
}

export const darkTheme = {
  backgroundGradient1: '#1D9CDB',
  backgroundGradient2: '#6CB3D6',
  primary:'#1E85B7',
  secondary:'#98DBEA',
  text: '#fff',
  secondaryText: '#1E85B7',
  background: '#FFFFFF',
  primaryCard:'#FFFFFF',
  positive: '#11B375',
  negative: '#FF6464',
  inputText:'#6B7280',
  inputText2:'#919BAE',
  errorText:'',
  keypadButton:'#F1F1F1',
  shadowColor: '#000000',
  borderColor: '#FFFFFF',
  tint: tintColorDark,
  tabIconDefault: '#6B7280',
  tabIconSelected: tintColorDark,
}

export interface AppTheme {
  backgroundGradient1: string,
  backgroundGradient2: string,
  primary: string,
  secondary: string,
  text: string,
  secondaryText: string,
  background: string,
  primaryCard: string,
  positive: string,
  negative: string,
  inputText:string,
  inputText2:string,
  errorText:string,
  keypadButton:string,
  shadowColor: string,
  borderColor: string,
  tint: string,
  tabIconDefault: string,
  tabIconSelected: string,
};
