export default {
  BEGIN_TEXT: "Let's track your spending",
  LOGIN_TEXT: "Let's save some pennies",
  CURRENT_BALANCE: "Current Balance",
  RUPEE_SIGN: "₹",
  INCOME: "Income",
  EXPENSES: "Expenses",
  RECENT_TRANSACTIONS: "Recent Transactions",
  SPEND_ANALYSIS: "Spend Analysis",
  SEE_ALL: "See All",
  WEEKLY: "Weekly",
  YEARLY: "Yearly",
  MONTHLY: "Monthly",
  USERNAME: "Username",
  FULLNAME: "Full Name",
  EMAIL: "Email",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password?",
  SUBMIT_OTP: "Submit OTP",
  ENTER_OTP: "Enter the OTP sent to your email",
  CHANGE_PASSWORD: "Change Password",
  SEND_EMAIL: "Send Reset Email",
  LOGIN: "Login",
  LOGOUT: "Log Out",
  SIGN_UP: "Sign up",
  SIGN_UP_SUCCESSFUL_TITLE: "You're in!",
  SIGN_UP_SUCCESSFUL_MESSAGE: "Let's get organized, We'll handle the math for you and you can focus on your goals.",
  SIGN_UP_SUCCESSFUL_BUTTON: "Login now",
  SIGN_IN_SUCCESSFUL_TITLE: "Good to see you again",
  SIGN_IN_SUCCESSFUL_MESSAGE: "Let\'s check in on your progress and keep that momentum going.",
  TOTAL_SPENDING: "Total Spending",
  MORE_THAN_LAST_MONTH: "more than last month",
  LESS_THAN_LAST_MONTH: "less than last month",
  LESS_THAN_LAST_WEEK: "less than last week",
  MORE_THAN_LAST_WEEK: "more than last week",
  EXPENSE_OVERVIEW: "Expense Overview",
  ADD_CATEGORY: "Add Category",
  PAUSE_NOTIFICATIONS: "Pause notifications",
  RESET_PASSWORD: "Reset password",
  DARK_MODE: "Dark mode",
  LANGUAGE: "Language",
  CURRENCY: "Currency",
  VERSION: "Version",
  ABOUT: "About",
  CATEGORY: "Category",
  AMOUNT: "Amount",
  DATE: "Date",
  NOTE: "Note",
  ADD: "Add",
  NAME: "Name",
  PERIOD: "Period",
  OR_CONTINUE_WITH: "Or continue with",
  WEEKLY_SPENDING_SUMMARY: "Weekly Spending Summary",
  TOP_SPENDING_DAY: "Top Spending Day",
  TOP_SPENDING_MONTH: "Top Spending Month",
  TRANSACTIONS: "Transactions",
  TOTAL_BUDGET_OVERVIEW: "Budget Overview",
  TOTAL_BUDGET: "Total Budget",
  REMAINING: "Remaining",
  ONGOING_BUDGET: "All Ongoing Budgets",
  OVERALL: "Overall",
  SAVE_BUDGET: "💰 Save Budget",
  UPDATE_BUDGET: "💰 Update Budget",
  SPENT: "spent",
  CATEGORY_WISE_SPENDING: "Category-wise Spending",
  STANDARD_BUDGET_WARNING:"In standard budgeting style you won't be able to add more than one budget for the same period, Delete the existing budget to update.",
  ADD_BUDGET_SUCCESSFUL_MESSAGE:"You better save your money 😉",
  ADD_BUDGET_SUCCESSFUL_TITLE:"Budget added",
  ADD_BUDGET_FAILED_TITLE:"Budget not added",
};
