export default{
    begin_text:'Let\'s track your spending',
    login_text:'Let\'s save some pennies',
    current_balance:'Current Balance',
    rupee_sign:'₹',
    income:'Income',
    expenses:'Expenses',
    recent_transactions:'Recent Transactions',
    spend_analysis:'Spend Analysis',
    see_all:'See All',
    weekly:'Weekly',
    yearly:'Yearly',
    username:'Username',
    fullname:'Full Name',
    email:'Email',
    password:'Password',
    forgot_password:'Forgot Password?',
    login:'Login',
    logout:'Log Out',
    sign_up:'Sign up',
    total_spending:'Total Spending',
    from_last_month:'from last month',
    expense_overview:'Expense Overview',
    add_category:'Add Category',
}